/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

//import Model.Contato;
//import DAO.SQLQuery;


import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;
import com.thoughtworks.xstream.security.NoTypePermission;
import com.thoughtworks.xstream.security.NullPermission;
import com.thoughtworks.xstream.security.PrimitiveTypePermission;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import DAO.ContatoCtrl;
import java.util.Arrays;

/**
 *
 * @author Aluno
 */
public class AgendaContados extends javax.swing.JFrame {
    
    private ArrayList<String[]> listaContatos = new ArrayList<>();

    /**
     * Creates new form AgendaContados
     */
    public AgendaContados() {
        initComponents();
        jP_Empresa.setVisible(false);
        this.ModoLeitura();
        this.setConfigTable();
        this.CarregarListaContatos();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jP_Titulo = new javax.swing.JPanel();
        jL_Titulo = new javax.swing.JLabel();
        jP_Contatos = new javax.swing.JPanel();
        jP_Telefone = new javax.swing.JPanel();
        jL_Telefone = new javax.swing.JLabel();
        jTF_Telefone = new javax.swing.JTextField();
        jTF_Celular = new javax.swing.JTextField();
        jL_Celular = new javax.swing.JLabel();
        jTF_Fax = new javax.swing.JTextField();
        jL_Fax = new javax.swing.JLabel();
        jP_Observacao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_Observacao = new javax.swing.JTextArea();
        jP_Empresa = new javax.swing.JPanel();
        jTF_EmpresaNome = new javax.swing.JTextField();
        jL_EmpresaNome = new javax.swing.JLabel();
        jL_Cargo = new javax.swing.JLabel();
        jTF_Cargo = new javax.swing.JTextField();
        jL_Nome = new javax.swing.JLabel();
        jTF_Nome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCB_TipoContato = new javax.swing.JComboBox<>();
        jChB_Favorito = new javax.swing.JCheckBox();
        jP_Registros = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Registros = new javax.swing.JTable();
        jL_Codigo = new javax.swing.JLabel();
        jTF_Codigo = new javax.swing.JTextField();
        jP_Botoes = new javax.swing.JPanel();
        jB_Insert = new javax.swing.JButton();
        jB_Gravar = new javax.swing.JButton();
        jB_Cancelar = new javax.swing.JButton();
        jB_Editar = new javax.swing.JButton();
        jB_Excluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jP_Titulo.setBackground(new java.awt.Color(0, 102, 102));

        jL_Titulo.setBackground(new java.awt.Color(255, 255, 255));
        jL_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jL_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jL_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Titulo.setText("Agenda de Contatos");

        javax.swing.GroupLayout jP_TituloLayout = new javax.swing.GroupLayout(jP_Titulo);
        jP_Titulo.setLayout(jP_TituloLayout);
        jP_TituloLayout.setHorizontalGroup(
            jP_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_TituloLayout.setVerticalGroup(
            jP_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_Titulo)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jP_Contatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Contatos"));

        jP_Telefone.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefones"));

        jL_Telefone.setText("Telefone:");

        jTF_Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_TelefoneActionPerformed(evt);
            }
        });

        jTF_Celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_CelularActionPerformed(evt);
            }
        });

        jL_Celular.setText("Celular:");

        jTF_Fax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_FaxActionPerformed(evt);
            }
        });

        jL_Fax.setText("Fax:");

        javax.swing.GroupLayout jP_TelefoneLayout = new javax.swing.GroupLayout(jP_Telefone);
        jP_Telefone.setLayout(jP_TelefoneLayout);
        jP_TelefoneLayout.setHorizontalGroup(
            jP_TelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_TelefoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_TelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Telefone)
                    .addComponent(jL_Celular)
                    .addComponent(jL_Fax)
                    .addGroup(jP_TelefoneLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jP_TelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_Fax, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jP_TelefoneLayout.setVerticalGroup(
            jP_TelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_TelefoneLayout.createSequentialGroup()
                .addComponent(jL_Telefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_Celular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_Fax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_Fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jP_Observacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Observações"));

        jTA_Observacao.setColumns(20);
        jTA_Observacao.setRows(5);
        jScrollPane1.setViewportView(jTA_Observacao);

        javax.swing.GroupLayout jP_ObservacaoLayout = new javax.swing.GroupLayout(jP_Observacao);
        jP_Observacao.setLayout(jP_ObservacaoLayout);
        jP_ObservacaoLayout.setHorizontalGroup(
            jP_ObservacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ObservacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_ObservacaoLayout.setVerticalGroup(
            jP_ObservacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jP_Empresa.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresa"));

        jTF_EmpresaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_EmpresaNomeActionPerformed(evt);
            }
        });

        jL_EmpresaNome.setText("Nome:");

        jL_Cargo.setText("Cargo:");

        jTF_Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_CargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_EmpresaLayout = new javax.swing.GroupLayout(jP_Empresa);
        jP_Empresa.setLayout(jP_EmpresaLayout);
        jP_EmpresaLayout.setHorizontalGroup(
            jP_EmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_EmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_EmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_EmpresaNome)
                    .addComponent(jL_Cargo)
                    .addGroup(jP_EmpresaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jP_EmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_EmpresaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_EmpresaLayout.setVerticalGroup(
            jP_EmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_EmpresaLayout.createSequentialGroup()
                .addComponent(jL_EmpresaNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_EmpresaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jL_Cargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jL_Nome.setText("Nome:");

        jLabel1.setText("Tipo Contato:");

        jCB_TipoContato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pessoal", "Profissional", "Outros" }));
        jCB_TipoContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_TipoContatoActionPerformed(evt);
            }
        });

        jChB_Favorito.setText("Favorito");
        jChB_Favorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChB_FavoritoActionPerformed(evt);
            }
        });

        jP_Registros.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros"));

        jTable_Registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Contato", "Favorito"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Registros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_Registros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_Registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_RegistrosMousePressed(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_RegistrosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Registros);

        javax.swing.GroupLayout jP_RegistrosLayout = new javax.swing.GroupLayout(jP_Registros);
        jP_Registros.setLayout(jP_RegistrosLayout);
        jP_RegistrosLayout.setHorizontalGroup(
            jP_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_RegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jP_RegistrosLayout.setVerticalGroup(
            jP_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );

        jL_Codigo.setText("Código:");

        jTF_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_CodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_ContatosLayout = new javax.swing.GroupLayout(jP_Contatos);
        jP_Contatos.setLayout(jP_ContatosLayout);
        jP_ContatosLayout.setHorizontalGroup(
            jP_ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ContatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_ContatosLayout.createSequentialGroup()
                        .addGroup(jP_ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ContatosLayout.createSequentialGroup()
                                .addComponent(jP_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jP_Observacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jP_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jP_Registros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jP_ContatosLayout.createSequentialGroup()
                        .addGroup(jP_ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Codigo)
                            .addGroup(jP_ContatosLayout.createSequentialGroup()
                                .addGroup(jP_ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTF_Codigo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTF_Nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                                    .addComponent(jL_Nome, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jP_ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jP_ContatosLayout.createSequentialGroup()
                                        .addComponent(jCB_TipoContato, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jChB_Favorito)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jP_ContatosLayout.setVerticalGroup(
            jP_ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ContatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_Codigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jP_ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Nome)
                    .addComponent(jLabel1))
                .addGap(5, 5, 5)
                .addGroup(jP_ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_TipoContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChB_Favorito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jP_Observacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_Empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_Registros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jP_Contatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jP_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_Contatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jB_Insert.setText("Inserir");
        jB_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_InsertActionPerformed(evt);
            }
        });

        jB_Gravar.setText("Gravar");
        jB_Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_GravarActionPerformed(evt);
            }
        });

        jB_Cancelar.setText("Cancelar");
        jB_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CancelarActionPerformed(evt);
            }
        });

        jB_Editar.setText("Editar");
        jB_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_EditarActionPerformed(evt);
            }
        });

        jB_Excluir.setText("Excluir");
        jB_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_BotoesLayout = new javax.swing.GroupLayout(jP_Botoes);
        jP_Botoes.setLayout(jP_BotoesLayout);
        jP_BotoesLayout.setHorizontalGroup(
            jP_BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BotoesLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jB_Insert)
                .addGap(18, 18, 18)
                .addComponent(jB_Gravar)
                .addGap(18, 18, 18)
                .addComponent(jB_Cancelar)
                .addGap(18, 18, 18)
                .addComponent(jB_Editar)
                .addGap(18, 18, 18)
                .addComponent(jB_Excluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_BotoesLayout.setVerticalGroup(
            jP_BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Insert)
                    .addComponent(jB_Gravar)
                    .addComponent(jB_Cancelar)
                    .addComponent(jB_Editar)
                    .addComponent(jB_Excluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jP_Botoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_Botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_CargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_CargoActionPerformed

    private void jTF_EmpresaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_EmpresaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_EmpresaNomeActionPerformed

    private void jTF_FaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_FaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_FaxActionPerformed

    private void jTF_CelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_CelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_CelularActionPerformed

    private void jTF_TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_TelefoneActionPerformed

    private void jChB_FavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChB_FavoritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChB_FavoritoActionPerformed

    private void jCB_TipoContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_TipoContatoActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) jCB_TipoContato.getSelectedItem();
        System.out.println(selectedItem);
        if(selectedItem.equals("Profissional")){
            jP_Empresa.setVisible(true);
        } else {
            jP_Empresa.setVisible(false);
        }
    }//GEN-LAST:event_jCB_TipoContatoActionPerformed

    private void jB_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_InsertActionPerformed
        // TODO add your handling code here:
        this.ModoEdicao();
        this.LimparLista();
    }//GEN-LAST:event_jB_InsertActionPerformed

    private void jB_GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_GravarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTable_Registros.getModel();
        Object [] rowData = new Object[4];
        String[] newContato = new String[10];
        
        int index = -1;
        
        newContato[0] = ""; //codigo
        newContato[1] = jTF_Nome.getText();
        newContato[2] = jCB_TipoContato.getSelectedItem().toString();
        newContato[3] = Boolean.toString(jChB_Favorito.isSelected());
        newContato[4] = jTF_Telefone.getText();
        newContato[5] = jTF_Celular.getText();
        newContato[6] = jTF_Fax.getText();
        newContato[7] = jTA_Observacao.getText();
        newContato[8] = ""; //empresa
        newContato[9] = ""; //cargo
        if (newContato[2].equals("Profissional")) {
            newContato[8] = jTF_EmpresaNome.getText();
            newContato[9] = jTF_Cargo.getText();
        }
        if(!jTF_Codigo.equals("")){
            index = buscaContatoIndex(listaContatos, jTF_Codigo.getText());
        }
        if(index >= 0){
            newContato[0] = jTF_Codigo.getText();
            listaContatos.set(index, newContato);            
            for (int i = modelo.getRowCount()-1; i >= 0; i--){
                modelo.removeRow(i);
            }
            for (String[] contato : listaContatos){
                rowData[0] = contato[0];
                rowData[1] = contato[1];
                rowData[2] = contato[2];
                rowData[3] = Boolean.getBoolean(contato[3]);
                
                modelo.addRow(rowData);
                
            }
            ContatoCtrl.saveContato(newContato);
        } else {
            newContato = ContatoCtrl.saveContato(newContato);
            listaContatos.add(newContato);
            
            rowData[0] = newContato[0];
            rowData[1] = newContato[1];
            rowData[2] = newContato[2];
            rowData[3] = Boolean.getBoolean(newContato[3]);
            
            modelo.addRow(rowData);
        }
        
        jTable_Registros.setModel(modelo);
        this.ModoLeitura();
    }//GEN-LAST:event_jB_GravarActionPerformed

    private void jB_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CancelarActionPerformed
        // TODO add your handling code here:
        this.ModoLeitura();
    }//GEN-LAST:event_jB_CancelarActionPerformed

    private void jB_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_EditarActionPerformed
        // TODO add your handling code here:
        this.ModoEdicao();
    }//GEN-LAST:event_jB_EditarActionPerformed

    private void jB_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ExcluirActionPerformed
        // TODO add your handling code here:
        int index = jTable_Registros.getSelectedRow();
        Object obj = jTable_Registros.getModel().getValueAt(index, 0);
        int indexContato = this.buscaContatoIndex(listaContatos, obj.toString());
        DefaultTableModel modelo = (DefaultTableModel) jTable_Registros.getModel();
        
        listaContatos.remove(indexContato);
        ContatoCtrl.deleteContato(obj.toString());
        modelo.removeRow(index);
    }//GEN-LAST:event_jB_ExcluirActionPerformed

    private void jTable_RegistrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_RegistrosMousePressed
        // TODO add your handling code here:
        this.loadComponents();
    }//GEN-LAST:event_jTable_RegistrosMousePressed

    private void jTF_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_CodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaContados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaContados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaContados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaContados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaContados().setVisible(true);
            }
        });
    } 
    
    private void ModoLeitura() {
        jB_Insert.setEnabled(true);
        jB_Editar.setEnabled(true);
        jB_Excluir.setEnabled(true);
        jTable_Registros.setEnabled(true);
        
        jB_Gravar.setEnabled(false);
        jB_Cancelar.setEnabled(false);
        jTF_Codigo.setEnabled(false);
        jTF_Nome.setEnabled(false);
        jTF_Telefone.setEnabled(false);
        jTF_Celular.setEnabled(false);
        jTF_Fax.setEnabled(false);
        jTF_EmpresaNome.setEnabled(false);
        jTF_Cargo.setEnabled(false);
        jTA_Observacao.setEnabled(false);
        jCB_TipoContato.setEnabled(false);
        jChB_Favorito.setEnabled(false);
    }
    
    private void ModoEdicao() {        
        jB_Gravar.setEnabled(true);
        jB_Cancelar.setEnabled(true);
        jTF_Codigo.setEnabled(false);
        jTF_Nome.setEnabled(true);
        jTF_Telefone.setEnabled(true);
        jTF_Celular.setEnabled(true);
        jTF_Fax.setEnabled(true);
        jTF_EmpresaNome.setEnabled(true);
        jTF_Cargo.setEnabled(true);
        jTA_Observacao.setEnabled(true);
        jCB_TipoContato.setEnabled(true);
        jChB_Favorito.setEnabled(true);
        
        jB_Insert.setEnabled(false);
        jB_Editar.setEnabled(false);
        jB_Excluir.setEnabled(false);
        jTable_Registros.setEnabled(false);
    }
    
    private void setConfigTable() {
        // tamanho das colunas
        TableColumn column = null;
        for (int i = 0; i < jTable_Registros.getColumnCount(); i++){
            column = jTable_Registros.getColumnModel().getColumn(i);
            switch (i) {
                case 0:
                    column.setPreferredWidth(100);
                    break;
                case 1:
                    column.setPreferredWidth(this.getWidth() - 360);
                    break;
                case 2:
                    column.setPreferredWidth(130);
                    break;
                case 3:
                    column.setPreferredWidth(130);
            }
        }
        
        // apenas uma row selecionável
        jTable_Registros.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    private String[] buscaContato(ArrayList<String[]> listaContatos, String codigo){
        for (String[] contato : listaContatos){
            if(contato[0].equals(codigo)){
                return contato;
            } 
        }
        return null;
    }
    
    private int buscaContatoIndex(ArrayList<String[]> listaContatos, String codigo){
        for (int i = 0; i < listaContatos.size(); i++){
            if(listaContatos.get(i)[0].equals(codigo)){
                return i;
            } 
        }
        return -1;
    }
    
    private void loadComponents() {
        int index = jTable_Registros.getSelectedRow();
        Object obj = jTable_Registros.getModel().getValueAt(index, 0);
        String[] contato = this.buscaContato(listaContatos, obj.toString());
        
        if (contato != null) {
            jTF_Nome.setText(contato[1]);
            jTF_Telefone.setText(contato[4]);
            jTF_Celular.setText(contato[5]);
            jTF_Fax.setText(contato[6]);
            if(contato[2].equals("Profissional")){
                jTF_EmpresaNome.setText(contato[8]);
                jTF_Cargo.setText(contato[9]);
            } else {
                jTF_EmpresaNome.setText("");
                jTF_Cargo.setText("");
            }
            jTA_Observacao.setText(contato[7]);
            jCB_TipoContato.setSelectedItem(contato[2]);
            jChB_Favorito.setSelected(Boolean.getBoolean(contato[3]));
            jTF_Codigo.setText(contato[0]);
        } else {
            JOptionPane.showMessageDialog(null, "Contato não encontrado " + obj);
        }
    }
    
    private void LimparLista() {
        jTF_Nome.setText("");
        jTF_Telefone.setText("");
        jTF_Celular.setText("");
        jTF_Fax.setText("");
        jTF_EmpresaNome.setText("");
        jTF_Cargo.setText("");
        jTA_Observacao.setText("");
        jCB_TipoContato.setSelectedIndex(0);
        jChB_Favorito.setSelected(false);
        jTF_Codigo.setText("");
    }
    
    private void CarregarListaContatos(){
        String [][] array = ContatoCtrl.getContato();
        listaContatos.addAll(Arrays.asList(array));
        DefaultTableModel modelo = (DefaultTableModel) jTable_Registros.getModel();
        Object [] newRow = new Object[4];
        for (String[] contato : listaContatos){
            newRow[0] = contato[0];
            newRow[1] = contato[1];
            newRow[2] = contato[2];
            newRow[3] = Boolean.getBoolean(contato[3]);

            modelo.addRow(newRow);
        }
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Cancelar;
    private javax.swing.JButton jB_Editar;
    private javax.swing.JButton jB_Excluir;
    private javax.swing.JButton jB_Gravar;
    private javax.swing.JButton jB_Insert;
    private javax.swing.JComboBox<String> jCB_TipoContato;
    private javax.swing.JCheckBox jChB_Favorito;
    private javax.swing.JLabel jL_Cargo;
    private javax.swing.JLabel jL_Celular;
    private javax.swing.JLabel jL_Codigo;
    private javax.swing.JLabel jL_EmpresaNome;
    private javax.swing.JLabel jL_Fax;
    private javax.swing.JLabel jL_Nome;
    private javax.swing.JLabel jL_Telefone;
    private javax.swing.JLabel jL_Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jP_Botoes;
    private javax.swing.JPanel jP_Contatos;
    private javax.swing.JPanel jP_Empresa;
    private javax.swing.JPanel jP_Observacao;
    private javax.swing.JPanel jP_Registros;
    private javax.swing.JPanel jP_Telefone;
    private javax.swing.JPanel jP_Titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTA_Observacao;
    private javax.swing.JTextField jTF_Cargo;
    private javax.swing.JTextField jTF_Celular;
    private javax.swing.JTextField jTF_Codigo;
    private javax.swing.JTextField jTF_EmpresaNome;
    private javax.swing.JTextField jTF_Fax;
    private javax.swing.JTextField jTF_Nome;
    private javax.swing.JTextField jTF_Telefone;
    private javax.swing.JTable jTable_Registros;
    // End of variables declaration//GEN-END:variables
}
